### ISSUE TITLE
example，cell_embeddings

### ISSUE THREAD

**Issue by lihaicheng7003** [calico/scBasset#10]
**examples/PBMC_multiome/evaluate.ipynb**
example：
![image](https://user-images.githubusercontent.com/61043072/185830599-3ab02370-d3f2-47c8-9214-bb82035f383d.png)
my results：
![mark](https://7niu.lihaicheng.cn/blog/20220822/1JgqFTYbvI3v.png)
When I run cell embeding in the umap results are a little different, data: **pbmc_ad.h5ad, pbmc_model.h5** (examples/download.ipynb downloaded)
I guess it might be a problem with the parameters of `sc.tl.umap(ad)`, but I have made many attempts and still can't change it. Can you provide a little advice? Thanks

**Comment by hy395** [comment]
Hi @lihaicheng7003 ,

Unfortunately, I am not able to reproducible this particular issue. If you git pull a fresh scBasset repo, run "download.ipynb" and "evaluate.ipynb", would you be able to reproduce the issue?

For debugging, I don't see any issue in your code computing the umap. Could you verify the proj matrix? The matrix is directly taken from the downloaded model, so it should be the same.
Here's the first 10 columns and 10 rows of the proj matrix:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/5845484/186334316-dd98cc2e-063b-43b8-93b1-b203246fb5d0.png">

Do you have the same proj matrix?

**Comment by hy395** [comment]
Hi,

I verified that the MD5 is same. db34a4c5bb715204ff8b6a7ebb5e1121
Could you share the full script of your workflow?

**Comment by lihaicheng7003** [comment]
Sorry, the matrix is the same, I had a mistake before, I said the matrix was different because I used my own trained model.

I found the reason, it was the **scanpy** version, before I used scanpy=1.7.1 and had different results, after updating to scanpy=1.9,1, the results were the same as yours.
test1: scanpy=1.7.1
test2: scanpy=1.9,1
https://drive.google.com/drive/folders/15Kn0c6_bsZHlfgqzkIk4mbKcGfIU0p06?usp=sharing

Thank you for always replying

**Comment by hy395** [comment]
Glad you figure out the solution. For your reference, I think this is an issue with the umap package:
https://scanpy.discourse.group/t/umap-incorrectly-installed/663

**Comment by lihaicheng7003** [comment]
gain a new knowledge
