### ISSUE TITLE
Mouse brain dataset processing

### ISSUE THREAD

**Issue by fym0503** [calico/scBasset#15]
Hi, Could you please share how you preprocess the mouse brain 5k dataset ? only the scripts for PBMC multiome and buen2018 dataset processing are provided. Thanks !

**Comment by hy395** [comment]
Hi @fym0503 , the two questions you have are more regarding the manuscript rather than the github code here. Could you share your email address? and so I can share the information via email.

Best,
Han

**Comment by fym0503** [comment]
Hi, Thanks for sharing ! My email is yimin.fan at mail.mcgill.ca
