### ISSUE TITLE
How does StochasticShift(3) work? Isn't 3bp a very small shift?

### ISSUE THREAD

**Issue by vitkl** [calico/scBasset#17]
Hi

Very cool modelling work. I am trying to understand the motivation behind using very small shifts (3bp):
https://github.com/calico/scBasset/blob/c15bec3a73fa1e04822db723338d234ca9d384ce/scbasset/utils.py#L200

I understand why shift should improve robustness in principle but my intuition was that you need large shifts (50-100bp). Could you please explain the reasoning behind using very small shifts?

**Comment by hy395** [comment]
Hi,

The stochastic shift is a way for data augmentation as you know. In scBasset, 3bp shift improves the robustness and performance of the model. We use small shift to make sure the label is still the same, and so we haven't explored large shifts since local accessibility may change at that distance.

**Comment by vitkl** [comment]
Thanks for responding @hy395!
Do you mean that you empirically see that 3bp shifts help? I don't fully understand why 3bp augmentation would have strong effects - because it doesn't substantially change the sequence shown to the model. Could this effect be specific to multi-layer CNN? (as opposed to one-layer CNN such as ExplaiNN)

**Comment by davek44** [comment]
Small shifts change the boundaries of the max pooling windows throughout the model's convolution blocks, which can have a surprisingly large influence on the results. We train with this augmentation to help the model be robust to these sorts of shifts and to obstruct it from memorizing the sequences. For models that don't use discrete pooling operations, small shifts wouldn't matter as much.

**Comment by vitkl** [comment]
Thank you for explaining @davek44! Now this makes sense.
