### ISSUE TITLE
Installing scBasset

### ISSUE THREAD

**Issue by sanghoonleeeins** [calico/scBasset#3]
Hi, 

I followed the installation instruction and I think I installed scBasset without any error. But, I couldn't verify that scBasset is correctly installed or not.  Please see the error message below.  Could you help me with how I can verify its installation?   I am using a supercomputer at my university and I have  installed some conda packages myself successfully.  But, installing a package through 'pip install' is first time.  I guess it is because I don't have sudo authority..?  But, I didn't get any error message in git clone and  "pip install -e scBasset"

(scbasset) [biotech@bridges2-login011 4_scBasset_scATACseq]$ python
Python 3.8.6 (default, Dec 17 2020, 16:57:01)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scbasset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scbasset'
>>>

Thank you, 
Sanghoon

**Comment by hy395** [comment]
turns out this is a system config issue unrelated to scBasset. I'll close this.
