### ISSUE TITLE
batch correction scBassset-BC

### ISSUE THREAD

**Issue by willey2020** [calico/scBasset#6]
Hello! Could I ask if the scBasset-BC method is in this repo? My data has strong batch effect with 2 assays. is it possible to try BC with scBasset? Thank you!

**Comment by willey2020** [comment]
I found
def make_model_bc()
I guess this is for the batch correction. Could I ask if there is a short tutorial for it, thank you so much!

**Comment by hy395** [comment]
Hi, 

Yes, make_model_bc() is for batch correction. And for extracting cell embeddings, imputation, and TF activity inference, there is a bc option which indicate whether the model is trained as scBasset-BC or not. Sure, I'm happy to upload a tutorial for batch correction shortly (today or tomorrow). I'll give you an update then.

**Comment by hy395** [comment]
Hi, I just updated the repo, added a very simple tutorial on how to run scBasset-BC. Hope this can already get you started. I'll add more evaluation later.

**Comment by willey2020** [comment]
Thank you so much again! It is super clear and very helpful! I will try it with my batched data. 
Thank you again for making this great architecture and analysis method!
